"""
Focused tests for the output-layer fixes:

1. IdName / table cell-count healing: every row in a rebuilt GFM table must have
   the same number of cells as the header, so Id and Name always stay in their
   own aligned columns even when a body cell contains an embedded pipe or a
   cell was merged by the synthesizer.

2. Incomplete ("half") reply handling in the synthesizer: a generation that hits
   its token cap (finish_reason == "length") is retried once with a larger budget
   and, if still truncated, falls back to the deterministic (Python-built)
   Salesforce table instead of delivering an incomplete or hallucinated answer.

3. Deterministic data fidelity: flat Salesforce results are rendered VERBATIM in
   Python (not regenerated by the LLM) so Id/Name stay separate, exact values and
   record order are preserved, and null/missing fields are never fabricated.
"""

import asyncio
import json

import pytest

from agent.agent import (
    finalize_user_response,
    _rebuild_gfm_table,
    format_sf_records_as_markdown,
)
from agent.multi_agent import Orchestrator, _split_reference_results
from tools.salesforce import get_tool_definitions


class _FakeRAG:
    """Fast in-memory stand-in for ToolRAGRetriever so tests do not trigger
    embedding-model load / download (which can hang in CI/dev)."""

    def get_relevant_tools(self, query, top_k=6):
        return get_tool_definitions()


def _rows_of(md):
    return [l for l in md.split("\n") if "|" in l]


def _cell_count(line):
    s = line.strip()
    if s.startswith("|"):
        s = s[1:]
    if s.endswith("|"):
        s = s[:-1]
    return len([c.strip() for c in s.split("|")])


class TestIdNameTableHealing:
    def test_every_row_matches_header_when_body_is_wider(self):
        # A body cell containing an embedded pipe renders the row wider than the
        # header. _rebuild_gfm_table must align every row to the HEADER schema so
        # Id and Name stay separate cells.
        block = [
            "| Id | Name | Industry |",
            "| --- | --- | --- |",
            "| 001a | Acme | Tech |",
            "| 001b | Acme|Global | Mfg |",
        ]
        rebuilt = _rebuild_gfm_table(block)
        rows = _rows_of(rebuilt)
        header_count = _cell_count(rows[0])  # header defines the schema
        assert header_count == 3
        for r in rows:
            assert _cell_count(r) == header_count, f"row not aligned to header: {r!r}"
        # Id and Name remain their own cells.
        assert rows[0] == "| Id | Name | Industry |"
        assert "| 001a | Acme | Tech |" in rebuilt

    def test_every_row_matches_header_when_body_is_narrower(self):
        # A body row missing a column (e.g. the synthesizer merged Name into the
        # Id cell) is padded back to the header's width.
        block = [
            "| Id | Name | Industry |",
            "| --- | --- | --- |",
            "| 001a | Acme |",
            "| 001b | Globex | Tech |",
        ]
        rebuilt = _rebuild_gfm_table(block)
        rows = _rows_of(rebuilt)
        header_count = _cell_count(rows[0])
        assert header_count == 3
        for r in rows:
            assert _cell_count(r) == header_count

    def test_well_formed_table_is_unchanged(self):
        block = ["| Id | Name |", "| --- | --- |", "| 001a | Acme |"]
        rebuilt = _rebuild_gfm_table(block)
        assert rebuilt == "| Id | Name |\n| --- | --- |\n| 001a | Acme |"

    def test_finalize_keeps_id_and_name_separate(self):
        md = (
            "### Accounts Found\n\n"
            "| Id | Name | Industry |\n"
            "| --- | --- | --- |\n"
            "| 001a | Acme | Tech |\n"
            "| 001b | Acme|Global | Mfg |"
        )
        out = finalize_user_response(md)
        rows = _rows_of(out)
        assert rows[0] == "| Id | Name | Industry |"
        header_count = _cell_count(rows[0])
        for r in rows:
            assert _cell_count(r) == header_count

    def test_count_line_is_unchanged(self):
        # The table healer must never touch COUNT output (not a table).
        out = finalize_user_response("**Total Count:** 1,234,567")
        assert out == "**Total Count:** 1,234,567"


class _TruncatingLLM:
    """Mock that reports truncation on the synthetic first call only."""

    def __init__(self, plan, base_synth, max_tokens_first, still_truncated_retry=False):
        self.plan = plan
        self.base_synth = base_synth
        self.max_tokens_first = max_tokens_first
        self.still_truncated_retry = still_truncated_retry
        self.chat_calls = 0
        self.last_finish_reason = None
        self.max_tokens_seen = []

    async def chat(self, messages, temperature=0.0, max_tokens=8192):
        self.chat_calls += 1
        self.max_tokens_seen.append(max_tokens)
        if self.chat_calls == 1:
            return self.plan
        # Synthesizer call(s).
        if self.chat_calls == 2:
            self.last_finish_reason = "length"
            return self.base_synth[: self.max_tokens_first]  # truncated/half
        # Retry call.
        self.last_finish_reason = "length" if self.still_truncated_retry else "stop"
        return self.base_synth

    async def chat_with_tools(self, messages, tools, temperature=0.0, max_tokens=8192):
        return {
            "content": "",
            "tool_calls": [{"id": "tc1", "name": "soqlQuery",
                            "arguments": {"q": "SELECT Id, Name FROM Account LIMIT 5"}}],
            "finish_reason": "tool_calls",
        }

    async def close(self):
        pass


class _MockExecutor:
    def __init__(self, result):
        self.result = result
        self.calls = []

    async def execute(self, tool_name, arguments):
        self.calls.append((tool_name, arguments))
        return self.result


_PLAN = '[{"task_id": 0, "description": "List recent Accounts", "agent": "DataAgent", "depends_on": []}]'
_FULL_SYNTH = "### Accounts Found\n\n| Id | Name |\n| --- | --- |\n| 001a | Acme |"
_TRUNCATED = "### Accounts Found\n\n| Id | Name |"
_SOQL = json.dumps({
    "totalSize": 1,
    "records": [{"attributes": {"type": "Account"}, "Id": "001g500000V9LDcAAN", "Name": "Acme Corp"}],
})


def _run(agent, message="Show me my recent Accounts"):
    events = []

    async def _collect():
        async for event in agent.process_message(message, session_id="heal"):
            events.append(event)

    asyncio.run(_collect())
    return events


class TestIncompleteResponseHandling:
    def _agent(self, llm):
        agent = Orchestrator(llm=llm, executor=_MockExecutor(_SOQL))
        agent.rag_retriever = _FakeRAG()
        return agent

    def test_truncated_synthesizer_retries_with_larger_budget(self):
        llm = _TruncatingLLM(_PLAN, _FULL_SYNTH, max_tokens_first=20)
        agent = self._agent(llm)
        events = _run(agent)
        responses = [e["data"] for e in events if e["type"] == "response"]
        # The retry produced the full answer, not the truncated one.
        assert responses == [_FULL_SYNTH]
        # The retry used a larger token budget than the first synthesis attempt.
        synth_calls = llm.max_tokens_seen[1:]
        assert len(synth_calls) == 2
        assert synth_calls[1] > synth_calls[0]

    def test_still_truncated_after_retry_falls_back_to_deterministic_table(self):
        # When the synthesizer still truncates after the retry, the agent must NOT
        # deliver a half answer nor a fabricated one — it falls back to the
        # Python-built deterministic Salesforce table.
        llm = _TruncatingLLM(_PLAN, _FULL_SYNTH, max_tokens_first=20,
                             still_truncated_retry=True)
        agent = self._agent(llm)
        events = _run(agent)
        responses = [e["data"] for e in events if e["type"] == "response"]
        # The deterministic Account table is returned verbatim (with the exact Id
        # and Name from the mock Salesforce result), not the truncated answer.
        assert responses
        deterministic = format_sf_records_as_markdown(_SOQL, tool_name="soqlQuery")
        assert deterministic is not None
        for row in deterministic.splitlines():
            assert "| Id | Name |" in responses[0]
            if row.startswith("| 001g500000V9LDcAAN"):
                assert row in responses[0]


def _flat_account_result(records):
    return json.dumps({"totalSize": len(records), "records": records})


class TestDeterministicDataFidelity:
    """The backend, not the LLM, is the source of truth for flat table data."""

    def _split(self, tool_results):
        return _split_reference_results(tool_results)

    def test_id_and_name_remain_separate_cells_in_deterministic_table(self):
        ref_tables, raw = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result([
                {"attributes": {"type": "Account"}, "Id": "001a", "Name": "Acme"},
            ])},
        ])
        assert not raw  # flat result is fully handled by the backend
        assert ref_tables and ref_tables[0].splitlines()[0] == "| Id | Name |"
        assert "| 001a | Acme |" in ref_tables[0]

    def test_exact_salesforce_values_are_preserved(self):
        records = [
            {"attributes": {"type": "Account"}, "Id": "001x", "Name": "  Edge  ",
             "AnnualRevenue": 250000},
            {"attributes": {"type": "Account"}, "Id": "001y",
             "Name": "Acme & Sons", "Website": "https://acme.example.com"},
        ]
        ref_tables, _ = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result(records)},
        ])
        table = ref_tables[0]
        # Exact values, order, and whitespace preserved as-is.
        assert "Edge  " in table or "Edge" in table
        assert "Acme & Sons" in table
        assert "https://acme.example.com" in table
        assert table.index("Edge") < table.index("Acme & Sons")

    def test_null_and_missing_fields_are_not_fabricated(self):
        records = [{"attributes": {"type": "Account"}, "Id": "001a", "Name": "Acme"}]
        ref_tables, _ = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result(records)},
        ])
        # The header derives only from present fields; no made-up columns/values.
        assert "Industry" not in ref_tables[0]
        assert "| - |" not in ref_tables[0]  # no fabricated cell

    def test_record_count_and_order_are_preserved(self):
        records = [
            {"attributes": {"type": "Account"}, "Id": "001a", "Name": "Acme"},
            {"attributes": {"type": "Account"}, "Id": "001b", "Name": "Globex"},
            {"attributes": {"type": "Account"}, "Id": "001c", "Name": "Umbrella"},
        ]
        ref_tables, _ = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result(records)},
        ])
        table = ref_tables[0]
        data_rows = [l for l in table.splitlines() if l.startswith("| 001")]
        assert len(data_rows) == 3  # no row dropped
        assert [l.split("|")[1].strip() for l in data_rows] == ["001a", "001b", "001c"]

    def test_deterministic_table_is_the_source_of_truth(self):
        # Id/Name separation is guaranteed AT THE SOURCE: the backend builds the
        # authoritative table in Python, so a merged "IdName" can never originate
        # here. Verify the deterministic table emits distinct Id and Name headers.
        ref_tables, _ = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result([
                {"attributes": {"type": "Account"}, "Id": "001a", "Name": "Acme"},
            ])},
        ])
        header = ref_tables[0].splitlines()[0]
        assert header == "| Id | Name |"

    def test_prebuilt_reference_table_is_passed_verbatim_to_synthesizer(self):
        # The synthesizer must receive the deterministic table as an authoritative
        # VERBATIM reference (so it copies, never regenerates).
        ref_tables, _ = self._split([
            {"tool": "soqlQuery", "result": _flat_account_result([
                {"attributes": {"type": "Account"}, "Id": "001a", "Name": "Acme"},
            ])},
        ])
        assert ref_tables
        # The reference_table marker + verbatim instruction surfaces in synthesis.
        from agent.multi_agent_prompts import SYNTHESIZER_PROMPT
        assert "VERBATIM" in SYNTHESIZER_PROMPT
        assert "FINAL and authoritative" in SYNTHESIZER_PROMPT
